### ISSUE TITLE
Dependency injection and strict mode problem

### ISSUE THREAD

**Issue by eduardmartinez** [jakubrohleder/angular-jsonapi#14]
Hi. I've recently updated the package with bower but it throws an error about strict mode and dependency injection. All worked well on alpha.4 but I made the update and it broke. Also I noticed you updated bower.json file to alpha.6 version but when I make the update, it shows alpha.5. Is anything wrong with the file or in somewhere else? Does the alpha.6 fix the D.I. error?

Thanks in advance.

**Comment by jakubrohleder** [comment]
My fault, it released .5 with a bug, uploaded a fix as .6 but forgot to upload the 1.0.0-alpha.6 tag. Try `bower update angular-jsonapi` now :)

**Comment by eduardmartinez** [comment]
Uploaded and running! I like that new way of defining services. It's all grouped into the same service and avoid those long names. Thank you very much.

**Comment by jakubrohleder** [comment]
You're welcome, I'm glad that you like this package!

In case you have any further questions don't hesitate to post an issue ;)
