### ISSUE TITLE
Live Demo seems to be down

### ISSUE THREAD

**Issue by SirMaster** [jakubrohleder/angular-jsonapi#15]
Hi, this looks pretty cool and am really interested in this, just wanting to play a bit with the live demo, but it seems to broken : http://jakubrohleder.github.io/angular-jsonapi/

In the console I see : 

```
Error: [$injector:unpr] Unknown provider: eProvider <- e <- $q
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20%24q
```

Any change to get it working?

**Comment by jakubrohleder** [comment]
It's up now :)

This issue is related to bug described in #14, not only I forgot to upload tags, but also rebuilt demo. Sorry.

**Comment by SirMaster** [comment]
Looks great! Thx. Now it's time to play!
