### ISSUE TITLE
Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by LavaToaster** [jakubrohleder/angular-jsonapi#16]
In the [source](https://github.com/jakubrohleder/angular-jsonapi/blob/develop/src/errors/source-error/source-error.factory.js) and [validation](https://github.com/jakubrohleder/angular-jsonapi/blob/develop/src/errors/validation-error/validation-error.factory.js) error factories, a call is made to Error.captureStackTrace which doesn't exist in a normal browser.

It causes any validation errors that happen to error out.

I'm unsure if you meant to use something else there, or if they're a relic from something else, so I didn't submit a PR for this.

**Comment by jakubrohleder** [comment]
To be true I can't remember what was the purpose of this. I suppose it is some kind of relic and can be safely removed.

It would be cool if you submit PR that removes those lines ;).
