### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by jakubrohleder** [jakubrohleder/angular-jsonapi#3]
Place for discussions about possible improvements / additions / api or roadmap changes for the package.

**Comment by hedder** [comment]
As per the spec, jsonapi can include <a href="http://jsonapi.org/format/#document-meta">meta</a>, or <a href="http://jsonapi.org/format/#document-links">links</a>.
Current implementation cuts them off. Would be nice to have them.

**Comment by jakubrohleder** [comment]
Fixed, now each get/refresh/link etc. request is resolved with meta.

After some consideration I think its better to create a new issue for each improvement, so they can be closed individually. Once again sorry for the mess.

**Comment by jsenecal** [comment]
You could use this issue to reference the other ones though...
