### ISSUE TITLE
Setting custom headers

### ISSUE THREAD

**Issue by mustela** [jakubrohleder/angular-jsonapi#30]
As far I can see, it is not possible to set a custom header for the resources calls, right? If not, is there any workaround?

Thanks!

**Comment by guilleva** [comment]
I didn't find a way to do it through angular-jsonapi, but this is how I did it:

``` javascript
$http.defaults.headers.common['X-API-TOKEN'] = 'XXXXXXXX'
$http.defaults.headers.common['Accept'] = 'application/vnd.api+json'
$http.defaults.headers.post['Content-Type'] = 'application/vnd.api+json'
$http.defaults.headers.put['Content-Type'] = 'application/vnd.api+json'
```

[More info](https://docs.angularjs.org/api/ng/service/$http#setting-http-headers)

**Comment by mustela** [comment]
Thanks! I did the same thing.
