### ISSUE TITLE
Uncaught ReferenceError: Parse is not defined

### ISSUE THREAD

**Issue by pablorsk** [jakubrohleder/angular-jsonapi#35]
When I install the library in my project, console says:

```
Uncaught ReferenceError: Parse is not defined
```

I follow these steps:

```
bower install angular-jsonapi --save
```

and I add this modules to my project

``` javascript
        'angular-jsonapi',
        'angular-jsonapi-rest',
        'angular-jsonapi-local',
        'angular-jsonapi-parse',
```

Any ideas? Thanks....

**Comment by mustela** [comment]
The lib can use [parse.com](https://github.com/jakubrohleder/angular-jsonapi#sourceparse) so if you don't need it, just remove the `angular-jsonapi-parse` module. 

Hope it helps!

**Comment by pablorsk** [comment]
Thanks @mustela, I try removing 'angular-jsonapi-parse' but the problem persist.

```
Uncaught ReferenceError: Parse is not defined
```

The error is in angular-jsonapi.js line 267:

```
(function() {
  'use strict';

  /* global Parse: false */
  angular.module('angular-jsonapi-parse', ['angular-jsonapi'])
    .constant('Parse', Parse);
})();
```

Thanks again....

**Comment by mustela** [comment]
Hey @pablorsk are you still having issues?

**Comment by pablorsk** [comment]
Yeap :'(. I'm trying with https://github.com/goodbomb/angular-gulp-browserify-starter/, maybe angular-json is not ready for browserify.

**Comment by pablorsk** [comment]
I'm trying, now, with https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate, maybe angular-json is not ready for browserify.

someone used angular-jsonapi with browserify?

**Comment by marsohod** [comment]
+1

**Comment by yves-s** [comment]
Hey @pablorsk, you have to install and include the dependencies/modules `parse`, `pluralize` and `validate`:
**Install dependencies**

``` bash
bower install --save parse pluralize vaildate
```

**Include sources**

``` html
<script src="lib/parse/parse.js" charset="utf-8"></script>
<script src="lib/pluralize/pluralize.js" charset="utf-8"></script>
<script src="lib/validate/validate.js" charset="utf-8"></script>
<script src="lib/angular-jsonapi/dist/angular-jsonapi.js"></script>
```

UPDATE:
You also have to install and include 

``` bash
bower install --save angular-uuid4
```

``` html
<script src="lib/angular-uuid4/angular-uuid4.js"></script>
```

**Comment by karneaud** [comment]
@pablorsk did this work for you? I am using the same browserify boilerplate. Can't seem to get it to work

**Comment by pablorsk** [comment]
No, we never can use angular-jsonapi with https://github.com/goodbomb/angular-gulp-browserify-starter/ or https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate.

But now, we use this generator: https://github.com/Swiip/generator-gulp-angular, and WORK REALLY GREAT!
