### ISSUE TITLE
Type of id field, currenty only uuid4 is supported.

### ISSUE THREAD

**Issue by hedder** [jakubrohleder/angular-jsonapi#4]
### Type of id field, currenty only uuid4 is supported.

However, according to <a href="http://jsonapi.org/format/#document-structure">official documentation</a>:

> Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings.

**Comment by jakubrohleder** [comment]
Yep, unfortunately this point breaks the specification. It was easier for me to implement only uuid ids at the beginning, as they allow you to generate id for a new object in the front end.

But after a quick look at the code I can tell it is probably not that hard to implement id of any type. I add this feature to 1.0.0-alpha.3 milestone.

**Comment by jsenecal** [comment]
@jakubrohleder you are allowed to generate IDs in the spec. when you create new elements but not required to. This is why the spec allow strings - it can be anything.

**Comment by jakubrohleder** [comment]
I know it, once again the 'only uuid4' policy was introduced just to make writing of the first package version easier (I thought I will use 'local id generation' more often).

**Comment by jsenecal** [comment]
@jakubrohleder sorry if I misunderstood you - did not want to be rude or anything. 
btw @hedder and I are working on the same project.

**Comment by jakubrohleder** [comment]
@jsenecal no problem! I'm not native, so I'm not surprised that sometimes I can get misunderstood. I'm glad that you guys want to commit to this project and find it useful ;)

**Comment by jakubrohleder** [comment]
@hedder @jsenecal I pretty much fixed this issue. From now on you can use `uuid4`, `int`, `string` or even custom id validator/generator.
