### ISSUE TITLE
How can I reset or change a sourceRest

### ISSUE THREAD

**Issue by pablorsk** [jakubrohleder/angular-jsonapi#40]
We need change the sourceRest in some case.

This is becouse we have a particular URL for each user, for example:
http://example.com/api/[user_loggued_id]/products

``` javascript
var restSynchro = $jsonapi.sourceRest.create('Rest synchronization',
                     'http://example.com/api/' + userid + '/products');
```

The var `userid` can change anytime, and we need change the REST URL.

Any ideas?

**Comment by max-SS** [comment]
+1

**Comment by pablorsk** [comment]
Solution: redefine jsonapi resourse again.
