### ISSUE TITLE
There's no way to access a promise

### ISSUE THREAD

**Issue by hedder** [jakubrohleder/angular-jsonapi#5]
I am using 
<code>resource.all(params)</code>
to fetch a list of objects.

However, I can not access the promise of this request. Is it possible to expose promise as a method like <a href="https://github.com/angular/bower-angular-resource/blob/master/angular-resource.js#L586-L616">angular resource does it, for example</a>.

**Comment by jakubrohleder** [comment]
The same problem occurs with `resource.get(id, params)`. 

This one is actually already at the 1.0.0-alpha.3 milestone tasks list. I got two ideas how to expose promise: 
- like angular.resource: `resource.all(params).promise.then(resolve, reject)...` (with or without $)
- by extending object with promise: `resource.all(params).then(resolve, reject)...`

I personally lean towards first option (without $, just to be consistent with the rest of the API). It's easiest to implement and does not lock on the $route (and ui-router) resolve. The second option is quite cool, but despite unobvious meaning of `.then` it locks on the resolve.

Uhh.. Long story short: If you do not disagree with my opinion this option will be added in the 1.0.0-alpha.3 as `resource.all(params).promise.then(resolve, reject)...`.

**Comment by hedder** [comment]
resource.all(params).promise.then makes perfect sense.

**Comment by hedder** [comment]
Fixed
