### ISSUE TITLE
Synchronization docs saying constructors take 1 parameter

### ISSUE THREAD

**Issue by hedder** [jakubrohleder/angular-jsonapi#8]
Docs shows this constructor with 1 parameter;
<code>
    var localeSynchronization = new AngularJsonAPISynchronizationLocal('AngularJsonAPI');
    var restSynchronization = new AngularJsonAPISynchronizationRest('/novels');
</code>
 however, there're 2 in the code

**Comment by jakubrohleder** [comment]
Fixed
