### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by hedder** [jakubrohleder/angular-jsonapi#9]
<a href="https://github.com/jakubrohleder/angular-jsonapi/blob/3575ab4039352d90b2dc6d868d465171b0ef7620/src/sources/source-rest.factory.js#L145">This</a> line creates a trailing slash. Is it possible to make it optional? Other URL calls in this project don't have a trailing slash

**Comment by jakubrohleder** [comment]
It's clearly a typo :)
